/** Agent lifecycle validation, Store calls, and human/NDJSON rendering. */
import { assertAgentId } from './agent-id.js';
import { CrewError } from './errors.js';
import { formatTimestamp, humanCell, writeJsonLine, writeLine, writeTable } from './format.js';
import type { Io } from './io.js';
import { isParticipantId, PARTICIPANT_IDS, type ParticipantId } from './participants.js';
import { resolveRole } from './roles.js';
import { type AgentRecord, openWorkspaceStore } from './store/index.js';
import { resolveWorkspaceRoot } from './workspace.js';

interface JoinOptions {
  readonly role?: string;
  readonly platform?: string;
  readonly resume: boolean;
  readonly json: boolean;
}

/** Hex token shape generated by the Launcher (`randomBytes(n).toString('hex')`). */
const LAUNCH_TOKEN_PATTERN = /^[0-9a-f]{32,128}$/;

/**
 * The reserved `CREW_LAUNCH_TOKEN` is injected into a live-launched pane's
 * environment by the Launcher; an Agent created in that pane is stamped with it
 * so a failed teardown can scope its reap. The variable is internal,
 * not user-facing, so a malformed value is ignored rather than failing a join.
 */
function launchTokenFrom(io: Io): string | undefined {
  const token = io.env.CREW_LAUNCH_TOKEN;
  return token !== undefined && LAUNCH_TOKEN_PATTERN.test(token) ? token : undefined;
}

function participant(platform: string | undefined): ParticipantId | undefined {
  if (platform === undefined) return undefined;
  if (!isParticipantId(platform)) {
    throw new CrewError(
      'UNSUPPORTED_PLATFORM',
      `unsupported Participant platform "${platform}"; expected one of ${PARTICIPANT_IDS.join(', ')}`,
    );
  }
  return platform;
}

function agentRecord(agent: AgentRecord): Record<string, unknown> {
  return {
    type: 'agent',
    schema_version: 1,
    id: agent.id,
    role: agent.role,
    platform_id: agent.platformId,
    status: agent.status,
    activity: agent.activity,
    joined_at: agent.joinedAt,
    last_seen: agent.lastSeen,
    archived_at: agent.archivedAt,
    stale_lease_count: agent.staleLeaseCount,
  };
}

function writeAgentTable(io: Io, agents: readonly AgentRecord[]): void {
  if (agents.length === 0) {
    writeLine(io, 'No agents.');
    return;
  }
  const rows = agents.map((agent) => [
    humanCell(agent.id),
    humanCell(agent.role),
    agent.platformId === null ? '-' : humanCell(agent.platformId),
    agent.activity,
    formatTimestamp(agent.lastSeen),
  ]);
  writeTable(io, ['ID', 'ROLE', 'PLATFORM', 'ACTIVITY', 'LAST SEEN'], rows);
}

function writeAgents(io: Io, agents: readonly AgentRecord[], json: boolean): void {
  if (json) {
    for (const agent of agents) writeJsonLine(io, agentRecord(agent));
    return;
  }
  writeAgentTable(io, agents);
}

/** `crew join`: validate configuration before opening/mutating the Store. */
export function runJoin(io: Io, id: string, options: JoinOptions): void {
  assertAgentId(id);
  const platformId = participant(options.platform);
  const role = options.resume ? options.role : (options.role ?? id);
  if (role !== undefined) resolveRole(io, role);

  const root = resolveWorkspaceRoot(io.cwd);
  const store = openWorkspaceStore(root, io.clock, io.random, io.onTransactionStep);
  try {
    // A stored Role can stop resolving when a custom project Role is removed.
    // Preserve resume's active/missing error precedence, but do not reactivate
    // an archived Agent whose Role no longer resolves.
    if (options.resume && role === undefined) {
      const existing = store.getAgent(id);
      if (existing?.status === 'archived') resolveRole(io, existing.role);
    }
    const launchToken = options.resume ? undefined : launchTokenFrom(io);
    const agent = store.joinAgent({
      id,
      ...(role !== undefined ? { role } : {}),
      ...(platformId !== undefined ? { platformId } : {}),
      resume: options.resume,
      ...(launchToken !== undefined ? { launchToken } : {}),
    });
    writeAgents(io, [agent], options.json);
  } finally {
    store.close();
  }
}

/** `crew leave`: archive one exact active Agent. */
export function runLeave(io: Io, id: string, options: { json: boolean }): void {
  assertAgentId(id);
  const root = resolveWorkspaceRoot(io.cwd);
  const store = openWorkspaceStore(root, io.clock, io.random, io.onTransactionStep);
  try {
    writeAgents(io, [store.leaveAgent(id)], options.json);
  } finally {
    store.close();
  }
}

/** `crew agents`: active-only by default, ordered by id. */
export function runAgentsList(io: Io, options: { all: boolean; json: boolean }): void {
  const root = resolveWorkspaceRoot(io.cwd);
  const store = openWorkspaceStore(root, io.clock, io.random, io.onTransactionStep);
  try {
    writeAgents(io, store.listAgents({ includeArchived: options.all }), options.json);
  } finally {
    store.close();
  }
}
